"""Derived domain-folder mirror (tracer bullet, WO 2026-08-22-031 Decision 3).

The authoritative discipline classification lives ONLY in each Work Object's
`domain:` frontmatter field (schema.py). This module builds a read-only,
regenerable index of that field -- one Markdown file per domain value,
listing the Work Objects whose `domain` list includes it.

This is deliberately NOT a symlink or junction tree. Both were tested and
ruled out in Decision 3: native Windows symlink creation requires admin
privilege ("Administrator privilege required for this operation"), Git
Bash's `ln -s` silently falls back to a plain copy that would quietly
become a second, stale source of truth, and Windows junctions are
directory-only -- structurally inapplicable to per-file mirroring. A
generated index file has no such failure mode and is trivially safe to
regenerate: it is always fully overwritten from frontmatter, never
hand-edited, and disposable without losing any information (deleting the
whole `domain/` tree and re-running sync reproduces it exactly).

A second, complementary CLI command queries frontmatter directly instead of
the generated mirror -- useful for scripting or a quick check without a sync
step first (WO 2026-08-22-036, the live-query flag deferred by Decision 3):
    - ``ws list [--domain VALUE ...]``

Both commands read the same frontmatter and use the same "list includes any
of the given values" filter semantics, so their results always agree.

Two CLI commands:
    - ``ws domain sync``
    - ``ws list``
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

from .schema import VALID_DOMAINS, parse_domain_field

_DOMAIN_LINE_RE = re.compile(r"^domain:\s*(.*)$", re.MULTILINE)
_ID_LINE_RE = re.compile(r"^id:\s*(.*)$", re.MULTILINE)
_TITLE_LINE_RE = re.compile(r"^title:\s*(.*)$", re.MULTILINE)
_STATUS_LINE_RE = re.compile(r"^status:\s*(.*)$", re.MULTILINE)
_STATE_LINE_RE = re.compile(r"^state:\s*(.*)$", re.MULTILINE)

GENERATED_HEADER = (
    "<!-- GENERATED by `ws domain sync` -- do not hand-edit. Regenerate with "
    "`ws domain sync`; this file is fully overwritten each run and carries "
    "no information not already in each Work Object's `domain:` frontmatter. -->\n"
)


def _find_work_studio_root() -> Path:
    """Walk upward from CWD to find .work-studio/ directory."""
    cwd = Path.cwd().resolve()
    for parent in [cwd] + list(cwd.parents):
        if (parent / ".work-studio").is_dir():
            return parent
    raise FileNotFoundError(
        ".work-studio/ not found in current directory or any parent. "
        "Run 'ws init' first to bootstrap the workspace."
    )


def _extract_frontmatter_field(content: str, pattern: re.Pattern) -> str:
    """Extract one scalar-or-bracketed frontmatter field's raw value by line scan.

    Deliberately bypasses schema.parse_frontmatter, which is documented as
    scalar-only and would not correctly read a bracketed `domain` list --
    see schema.parse_domain_field's docstring for why this field gets its
    own dedicated reader instead of extending the shared generic parser.
    """
    if not content.startswith("---"):
        return ""
    end = content.find("---", 3)
    if end == -1:
        return ""
    fm_text = content[:end]
    match = pattern.search(fm_text)
    if not match:
        return ""
    return match.group(1).strip()


def collect_domain_index(objects_dir: Path) -> Dict[str, List[Tuple[str, str, str]]]:
    """Scan the corpus and group Work Objects by declared domain.

    Returns {domain_value: [(wo_id, title, relative_path), ...]}, sorted by
    wo_id within each domain. Deterministic: sorted file order, matching the
    established full-corpus scan idiom already used by graph.py/validate.py.
    An object with no `domain:` field contributes to no domain -- absence
    here means "not classified", not "excluded" or "false".
    """
    index: Dict[str, List[Tuple[str, str, str]]] = {d: [] for d in VALID_DOMAINS}

    for obj_file in sorted(objects_dir.rglob("*.md")):
        try:
            content = obj_file.read_text(encoding="utf-8")
        except Exception:
            continue

        raw_domain = _extract_frontmatter_field(content, _DOMAIN_LINE_RE)
        if not raw_domain:
            continue
        values = [v for v in parse_domain_field(raw_domain) if v in VALID_DOMAINS]
        if not values:
            continue

        wo_id = _extract_frontmatter_field(content, _ID_LINE_RE) or obj_file.stem
        title = _extract_frontmatter_field(content, _TITLE_LINE_RE) or obj_file.stem
        rel_path = str(obj_file.relative_to(objects_dir.parent.parent))

        for value in values:
            index[value].append((wo_id, title, rel_path))

    for value in index:
        index[value].sort(key=lambda row: row[0])

    return index


def _render_domain_file(domain_value: str, entries: List[Tuple[str, str, str]]) -> str:
    lines = [GENERATED_HEADER, f"# Domain: {domain_value}\n"]
    if not entries:
        lines.append(
            "\nNo Work Objects currently declare this domain. This means "
            "not recorded, not necessarily absent -- classification is "
            "opt-in per WO 2026-08-22-031 Decision 1 (no retro-migration).\n"
        )
        return "".join(lines)
    lines.append(f"\n{len(entries)} Work Object(s):\n\n")
    for wo_id, title, rel_path in entries:
        lines.append(f"- `{wo_id}` — {title} ({rel_path})\n")
    return "".join(lines)


# ═══════════════════════════════════════════════════════════════════════════════
# ws domain sync
# ═══════════════════════════════════════════════════════════════════════════════


def cmd_domain_sync(args: argparse.Namespace) -> int:
    """Regenerate domain/<value>.md index files from frontmatter."""
    try:
        ws_root = _find_work_studio_root()
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    objects_dir = ws_root / ".work-studio" / "objects"
    domain_dir = ws_root / ".work-studio" / "domain"
    domain_dir.mkdir(exist_ok=True)

    index = collect_domain_index(objects_dir)

    written = 0
    classified_objects = set()
    for domain_value, entries in sorted(index.items()):
        out_file = domain_dir / f"{domain_value}.md"
        out_file.write_text(_render_domain_file(domain_value, entries), encoding="utf-8")
        written += 1
        for wo_id, _title, _path in entries:
            classified_objects.add(wo_id)

    print(f"Regenerated {written} domain index file(s) in {domain_dir.relative_to(ws_root)}/")
    print(f"{len(classified_objects)} Work Object(s) carry a domain classification.")
    return 0


# ═══════════════════════════════════════════════════════════════════════════════
# ws list
# ═══════════════════════════════════════════════════════════════════════════════


def collect_object_rows(objects_dir: Path) -> List[Dict[str, object]]:
    """Scan the corpus directly from frontmatter -- no generated mirror involved.

    Returns one row per object: {id, title, domain (list, possibly empty),
    status, state}, sorted by id. Uses the same scan/extract pattern as
    ``collect_domain_index`` so `ws list --domain X` and `ws domain sync`
    always agree on membership.
    """
    rows: List[Dict[str, object]] = []

    for obj_file in sorted(objects_dir.rglob("*.md")):
        try:
            content = obj_file.read_text(encoding="utf-8")
        except Exception:
            continue

        raw_domain = _extract_frontmatter_field(content, _DOMAIN_LINE_RE)
        values = [v for v in parse_domain_field(raw_domain) if v in VALID_DOMAINS] if raw_domain else []

        rows.append({
            "id": _extract_frontmatter_field(content, _ID_LINE_RE) or obj_file.stem,
            "title": _extract_frontmatter_field(content, _TITLE_LINE_RE) or obj_file.stem,
            "domain": values,
            "status": _extract_frontmatter_field(content, _STATUS_LINE_RE) or "",
            "state": _extract_frontmatter_field(content, _STATE_LINE_RE) or "",
        })

    rows.sort(key=lambda row: row["id"])
    return rows


def cmd_list(args: argparse.Namespace) -> int:
    """List Work Objects, optionally filtered by domain (live frontmatter query)."""
    try:
        ws_root = _find_work_studio_root()
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    filter_domains = [d for d in (getattr(args, "domain", None) or [])]
    for value in filter_domains:
        if value not in VALID_DOMAINS:
            print(
                f"Error: invalid domain value '{value}'. Valid values: "
                f"{', '.join(sorted(VALID_DOMAINS))}",
                file=sys.stderr,
            )
            return 1

    objects_dir = ws_root / ".work-studio" / "objects"
    rows = collect_object_rows(objects_dir)

    if filter_domains:
        rows = [r for r in rows if set(r["domain"]) & set(filter_domains)]

    if not rows:
        if filter_domains:
            print(f"No Work Objects found for domain(s): {', '.join(filter_domains)}")
        else:
            print("No Work Objects found.")
        return 0

    for row in rows:
        domain_display = f"[{', '.join(row['domain'])}]" if row["domain"] else "(none)"
        print(f"{row['id']}  {row['status']}/{row['state']}  {domain_display}  {row['title']}")

    print(f"\n{len(rows)} Work Object(s).")
    return 0
