#!/usr/bin/env python3
"""Generate platform adapter SKILL.md files from canonical core + platform overlays.

Dependency-free — uses only Python 3 standard library.

Usage:
    python3 tools/generate-adapters.py              # generate all adapters
    python3 tools/generate-adapters.py --check      # verify generated files match

Architecture:
    skills/core/<skill>/SKILL.md  →  canonical source (the portable core)
    adapters/<platform>/overlay.yaml  →  platform-specific metadata + mappings
    adapters/<platform>/skills/<skill>/SKILL.md  →  generated adapter
    adapters/<platform>/manifest.json  →  checksums (generated)

The generator:
    1. Copies the core skill body unchanged (decision logic, authority rules, schema)
    2. Replaces the YAML frontmatter with platform-specific metadata
    3. Appends a Platform Adapter section with tool mappings + declared limitations
    4. Produces byte-for-byte identical output on regeneration
"""

import hashlib
import json
import os
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = ROOT / "skills" / "core"
ADAPTERS_DIR = ROOT / "adapters"
VERSION_FILE = ROOT / "VERSION"
PLATFORMS = ["codex", "claude-code", "github-copilot"]
SKILL_NAMESPACE = "alawas"
SHARED_REFERENCES = [
    "MISSING-ARTIFACT-GAP.md",
    "AGREEMENT-LOOP.md",
    "SKILL-AWARE-GRILLING.md",
    "CAPABILITY-DEGRADATION.md",
    "CONSEQUENCE-AUTHORITY.md",
    "EVIDENCE-MODEL.md",
    "DIRECTOR-LANGUAGE.md",
]

# Kernel/overlay split: AGREEMENT-LOOP.md and SKILL-AWARE-GRILLING.md form the
# grilling overlay. They ship only with the grilling-session skill; all other
# skills get kernel-only output (Decision 3, WO 2026-07-26-004).
GRILLING_OVERLAY_REFS = {"AGREEMENT-LOOP.md", "SKILL-AWARE-GRILLING.md"}
GRILLING_CORE_NAME = "thinking-grilling-session"

# Epistemic reference variants (WO 2026-07-26-006)
EPISTEMIC_REF_DIR = ROOT / "references" / "epistemic"
EPISTEMIC_VARIANTS = {
    "high": "epistemic-rules-full.md",
    "medium": "epistemic-rules-essential.md",
    "low": "epistemic-rules-essential.md",
}

# epistemic-rules-full.md points to AGREEMENT-LOOP.md lines 98-105 for the
# canonical 6-tag table instead of restating it (WO 2026-08-15-011, closing a
# drift risk that already caused one incident: WO 2026-08-10-007). But
# AGREEMENT-LOOP.md itself ships only with the grilling-session skill
# (GRILLING_OVERLAY_REFS, WO 2026-07-26-004 Decision 3, ~756-line payload
# saving) — so the pointer would dangle in every other high-tier adapter
# copy. Extracting just these 8 lines at generation time (never hand-typed,
# so it cannot drift) keeps that payload boundary intact while making the
# pointer resolvable everywhere epistemic-rules-full.md ships.
AGREEMENT_LOOP_TAG_EXCERPT_START = 98
AGREEMENT_LOOP_TAG_EXCERPT_END = 105
AGREEMENT_LOOP_TAG_EXCERPT_FILENAME = "agreement-loop-tag-table-excerpt.md"


def extract_agreement_loop_tag_excerpt() -> bytes:
    """Extract the 6-tag definition lines from AGREEMENT-LOOP.md verbatim.

    Generated fresh on every run from the canonical source, so this excerpt
    cannot independently drift the way a hand-copied table could.
    """
    source = ROOT / "references" / "AGREEMENT-LOOP.md"
    lines = source.read_text().splitlines()
    excerpt = lines[AGREEMENT_LOOP_TAG_EXCERPT_START - 1 : AGREEMENT_LOOP_TAG_EXCERPT_END]
    header = (
        "<!-- Generated by tools/generate-adapters.py from "
        "references/AGREEMENT-LOOP.md "
        f"lines {AGREEMENT_LOOP_TAG_EXCERPT_START}-{AGREEMENT_LOOP_TAG_EXCERPT_END}. "
        "Do not hand-edit; edit the source and regenerate. -->\n\n"
    )
    body = "\n".join(excerpt) + "\n"
    return (header + body).encode("utf-8")

# Shared preamble sections (WO 2026-07-27-009).
# Sections whose common preamble lives in a shared reference file and is
# injected at generation time, so each core skill contains only its per-skill
# custom content.
SHARED_PREAMBLE_SECTIONS = {
    "## Consequence and authority rules":
        ROOT / "references" / "shared" / "consequence-authority-preamble.md",
    "## Grilling entry and stage lens":
        ROOT / "references" / "shared" / "grilling-entry-preamble.md",
    "## Work Object updates":
        ROOT / "references" / "shared" / "work-object-updates-preamble.md",
    "## Output template":
        ROOT / "references" / "shared" / "director-language-preamble.md",
}

TIER_ORDER = {"high": 3, "medium": 2, "low": 1}


def resolve_epistemic_tier(default_tier, wo_consequence=None):
    """Resolve the epistemic tier for a skill.

    Applies the same consequence-based escalation as model tier selection:
    actual_epistemic_tier = max(skill.default_tier, consequence_escalation(wo.consequence)).

    When wo_consequence is None, returns the skill's default tier (safe default
    for generation, since the WO context is not available at adapter-build time).
    """
    if wo_consequence is None:
        return default_tier

    consequence_escalation = {"low": "low", "meaningful": "medium", "high": "high"}
    escalated = consequence_escalation.get(wo_consequence, "low")

    if TIER_ORDER.get(escalated, 1) > TIER_ORDER.get(default_tier, 1):
        return escalated
    return default_tier


def epistemic_variant_filename(epistemic_tier: str) -> str:
    """Return the epistemic reference filename for the given tier."""
    return EPISTEMIC_VARIANTS.get(epistemic_tier, "epistemic-rules-essential.md")


def read_version() -> str:
    """Read the release version, pinned in the VERSION file.

    Read from a file (never derived from a clock or environment) so that
    regeneration is byte-for-byte deterministic.
    """
    if VERSION_FILE.exists():
        return VERSION_FILE.read_text().strip()
    return "0.0.0"


# ── Minimal YAML parser ──────────────────────────────────────────────────────

def parse_yaml(text: str) -> dict:
    """Parse a minimal YAML subset: mappings, sequences, scalars, comments.

    Only handles the overlay file format. Not a general-purpose YAML parser.
    """
    lines = text.split("\n")
    root = {}
    # Stack of (indent, container) — container is a dict or list.
    # stack[0] is always (0, root).
    stack = [(0, root)]

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Skip empty lines and comments
        if not stripped or stripped.startswith("#"):
            i += 1
            continue

        indent = len(line) - len(line.lstrip())

        # Pop entries deeper than current indent, but never pop the root
        while len(stack) > 1 and stack[-1][0] >= indent:
            stack.pop()

        container = stack[-1][1]

        # Sequence item
        if stripped.startswith("- "):
            raw_value = stripped[2:].strip()

            # Check for inline mapping: "- key: value" or "- key:"
            if ":" in raw_value and not (raw_value.startswith('"') or raw_value.startswith("'")):
                k, _, v = raw_value.partition(":")
                k = k.strip()
                v = v.strip()
                inline_map = {k: _parse_scalar(v) if v else {}}

                if isinstance(container, list):
                    container.append(inline_map)
                # Push so subsequent lines at higher indent go into this map.
                # The indent of the "- " line is the base indent for this mapping.
                stack.append((indent, inline_map))
            else:
                value = _parse_scalar(raw_value)
                if isinstance(container, list):
                    container.append(value)
            i += 1
            continue

        # Mapping key: value
        if ":" in stripped:
            key, _, val = stripped.partition(":")
            key = key.strip()
            val = val.strip()

            if val == "":
                # Nested block: peek ahead to determine list vs dict
                is_list = False
                for j in range(i + 1, len(lines)):
                    nline = lines[j]
                    nstripped = nline.strip()
                    if nstripped and not nstripped.startswith("#"):
                        if nstripped.startswith("- "):
                            is_list = True
                        break

                if is_list:
                    container[key] = []
                    stack.append((indent, container[key]))
                else:
                    container[key] = {}
                    stack.append((indent, container[key]))
            else:
                container[key] = _parse_scalar(val)

        i += 1

    return root


def _parse_scalar(val: str):
    """Parse a scalar YAML value."""
    if not val:
        return val
    if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
        return val[1:-1]
    if val.lower() in ("true", "yes", "on"):
        return True
    if val.lower() in ("false", "no", "off"):
        return False
    if val.lower() in ("null", "none", "~"):
        return None
    try:
        return int(val)
    except ValueError:
        pass
    try:
        return float(val)
    except ValueError:
        pass
    return val


# ── Frontmatter generation ───────────────────────────────────────────────────

def extract_canonical_description(core_skill_dir):
    """Extract the description field from a canonical SKILL.md frontmatter.

    Handles double-quoted strings, folded block scalars (``description: >``),
    and plain inline values.
    """
    text = (core_skill_dir / "SKILL.md").read_text()
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"No frontmatter found in {core_skill_dir}/SKILL.md")
    fm_text = parts[1]

    lines = fm_text.split("\n")
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("description:"):
            continue

        rest = stripped[len("description:"):].strip()

        # Double-quoted string
        if rest.startswith('"') and rest.endswith('"'):
            return rest[1:-1]

        # Block scalar: description: > or description: |
        if rest in (">", "|"):
            desc_lines = []
            key_indent = len(line) - len(line.lstrip())
            for j in range(i + 1, len(lines)):
                next_line = lines[j]
                next_stripped = next_line.strip()
                if not next_stripped or next_stripped.startswith("#"):
                    continue
                next_indent = len(next_line) - len(next_line.lstrip())
                if next_indent <= key_indent and ":" in next_stripped:
                    break
                desc_lines.append(next_stripped)
            return " ".join(desc_lines)

        # Plain inline value
        return rest

    raise ValueError(
        f"No description found in {core_skill_dir}/SKILL.md frontmatter")


def extract_default_tier(core_skill_dir):
    """Extract the default_tier field from a canonical SKILL.md frontmatter.

    Returns 'medium' as the default if no tier is declared.
    """
    text = (core_skill_dir / "SKILL.md").read_text()
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"No frontmatter found in {core_skill_dir}/SKILL.md")
    fm_text = parts[1]

    for line in fm_text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("default_tier:"):
            val = stripped[len("default_tier:"):].strip()
            if val in ("high", "medium", "low"):
                return val
            raise ValueError(
                f"Invalid default_tier '{val}' in {core_skill_dir}/SKILL.md")

    return "medium"


def generate_frontmatter(core_skill_dir, overlay):
    """Generate platform-specific YAML frontmatter.

    Extracts the description and default_tier from the canonical SKILL.md
    frontmatter — the single source of truth (Decision 87, Session 11).
    Includes the abstract tier declaration so platform loaders can resolve
    it to provider-specific models via the overlay's model_tiers mapping.
    """
    description = extract_canonical_description(core_skill_dir)
    short_desc = " ".join(description.split())
    default_tier = extract_default_tier(core_skill_dir)

    fm_add = overlay.get("frontmatter", {}).get("add", {})
    skill_name = core_skill_dir.name

    lines = ["---"]
    lines.append(f"name: {adapter_skill_name(skill_name)}")
    # JSON strings are valid quoted YAML scalars. Keeping the generated value
    # on one line avoids indentation-sensitive folded-block failures in skill
    # loaders while preserving quotes and Unicode deterministically.
    lines.append(f"description: {json.dumps(short_desc, ensure_ascii=False)}")
    lines.append(f"default_tier: {default_tier}")
    for k, v in sorted(fm_add.items()):
        lines.append(f"{k}: {v}")
    lines.append("---")

    return "\n".join(lines) + "\n"


# ── Platform adapter section ─────────────────────────────────────────────────

def required_capabilities(core_skill_dir):
    """Return capabilities declared by one core skill, preserving first use order."""
    body = extract_body(core_skill_dir / "SKILL.md")
    try:
        section = body.split("## Required capabilities", 1)[1].split("\n## ", 1)[0]
    except IndexError as exc:
        raise ValueError(
            f"Missing Required capabilities section: {core_skill_dir / 'SKILL.md'}"
        ) from exc

    declared = []
    for line in section.splitlines():
        if not line.startswith("- "):
            continue
        declaration = line.split("—", 1)[0]
        for capability in re.findall(r"`([^`]+)`", declaration):
            if capability not in declared:
                declared.append(capability)
    if not declared:
        raise ValueError(f"No required capabilities declared: {core_skill_dir.name}")
    return declared


def generate_adapter_section(overlay, required, default_tier="medium"):
    """Generate only invocation-relevant platform wiring for one skill."""

    lines = []
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Platform Adapter")
    lines.append("")
    lines.append("Invocation-relevant wiring only; installation and maintainer guidance live outside this file.")

    # Epistemic rules tier resolution
    epistemic_tier = resolve_epistemic_tier(default_tier)
    variant_file = epistemic_variant_filename(epistemic_tier)
    lines.append("")
    lines.append("### Epistemic rules")
    lines.append("")
    epistemic_labels = {
        "high": "full 6‑tag system",
        "medium": "essential 3‑tag system",
        "low": "essential 3‑tag system",
    }
    label = epistemic_labels.get(epistemic_tier, "essential 3‑tag system")
    lines.append(f"This skill uses the **{label}** (`references/epistemic/{variant_file}`).")
    lines.append("")
    lines.append(f"The epistemic tier is resolved from the skill's `default_tier` ({default_tier}).")
    lines.append("**Consequence-based escalation:** When a Work Object has `consequence: meaningful`,")
    lines.append("the epistemic tier is upgraded to at least `medium` (essential 3‑tag).")
    lines.append("When `consequence: high`, the epistemic tier is upgraded to the strongest")
    lines.append("available tier (full 6‑tag).")
    lines.append("`actual_epistemic_tier = max(skill.default_tier, consequence_escalation(wo.consequence))`.")
    lines.append("")

    # Model tier resolution
    model_tiers = overlay.get("model_tiers", {})
    prompt_budgets = overlay.get("prompt_budgets", {})
    if model_tiers:
        resolved_model = model_tiers.get(default_tier, model_tiers.get("medium", "—"))
        lines.append("### Model tier")
        lines.append("")
        lines.append(f"This skill declares `default_tier: {default_tier}`.")
        lines.append(f"The platform overlay resolves this to `{resolved_model}`.")
        if prompt_budgets:
            budget = prompt_budgets.get(default_tier, "—")
            lines.append(f"The prompt budget for this tier is approximately {budget} tokens (advisory).")
        lines.append("")
        lines.append("**Consequence-based escalation:** When a Work Object has `consequence: meaningful`,")
        lines.append("the effective tier is upgraded to at least `medium`. When `consequence: high`,")
        lines.append("the effective tier is upgraded to the strongest available model.")
        lines.append("`actual_tier = max(skill.default_tier, consequence_escalation(wo.consequence))`.")
    lines.append("")

    if overlay["platform"] == "codex":
        # Pin-resolution paragraph emitted for Codex only. Assumption: Claude
        # Code and GitHub Copilot skill loaders natively prefer project-pinned
        # over global without explicit prose instruction. UNVERIFIED — see
        # Decision 85 (Session 11). Verify per-platform before adding or
        # permanently omitting.
        lines.append("### Runtime pin resolution")
        lines.append("")
        lines.append("Codex can discover both user and repository skills with the same name.")
        lines.append("Before applying this skill, search upward from the current directory for")
        lines.append("`.work-studio/adapter.codex.lock`, stopping at the repository or filesystem")
        lines.append("boundary. Read its `dest` value and")
        lines.append("resolve `<dest>/<this-skill-name>/SKILL.md`. When that path differs from")
        lines.append("the currently loaded copy, **load and follow the pinned copy** before")
        lines.append("continuing. A matching legacy `adapter.lock` remains valid during migration.")
        lines.append("If the pinned file is unavailable, report the broken pin and")
        lines.append("stop instead of silently falling back to the global copy.")
        lines.append("")

    # Required capability mappings only.
    mappings = overlay.get("capability_mappings", {})
    caps = overlay.get("capabilities", {})
    lines.append("### Required capability mappings")
    lines.append("")
    lines.append("| Abstract capability | Platform tool | Classification |")
    lines.append("|---------------------|---------------|----------------|")
    for cap in required:
        if cap not in caps:
            raise ValueError(f"{overlay['platform']}: unclassified required capability: {cap}")
        tool = mappings.get(cap, "—")
        lines.append(f"| `{cap}` | `{tool}` | {caps[cap]} |")
    lines.append("")

    # Degradation behavior only for non-native capabilities this skill requires.
    non_native = {cap: caps[cap] for cap in required if caps[cap] != "native"}
    if non_native:
        lines.append("### Capability Degradation")
        lines.append("")
        lines.append("Apply `references/CAPABILITY-DEGRADATION.md`. Per-capability")
        lines.append("classifications and notes below.")
        lines.append("")

        for cap in non_native:
            classification = non_native[cap]
            tool = mappings.get(cap, "—")
            # Find matching declared limitation for the description
            desc = ""
            for lim in overlay.get("declared_limitations", []):
                if lim.get("capability") == cap:
                    desc = lim.get("description", "")
                    break
            lines.append(f"#### `{cap}` ({classification})")
            lines.append("")
            if tool and tool != "—":
                lines.append(f"- **Best-effort tool**: `{tool}`")
            if classification == "manual-fallback":
                lines.append("- **Behavior**: Pause and give one concrete manual instruction.")
                lines.append("- **Record**: Append History entry noting the capability gap, the")
                lines.append("  manual action taken, and what remains unverified.")
            elif classification == "unsupported":
                lines.append("- **Behavior**: Stop the affected path. Do not attempt or substitute.")
                lines.append("- **Record**: Note the platform limitation in the Work Object body.")
            if desc:
                lines.append(f"- **Note**: {desc}")
            lines.append("")

    return "\n".join(lines)


# ── Skill body extraction ────────────────────────────────────────────────────

def extract_body(filepath):
    """Extract the Markdown body after the YAML frontmatter.

    A SKILL.md file has:
        ---
        frontmatter
        ---
        body (everything after the second ---)
    """
    text = filepath.read_text()
    # Find the second ---
    parts = text.split("---", 2)
    if len(parts) >= 3:
        return parts[2].lstrip("\n")
    return text


# ── Authority block validation ────────────────────────────────────────────────

# Skills that describe gated actions and MUST have inline authority blocks
# referencing CONSEQUENCE-AUTHORITY.md at their action points.
# Per Decision 57 (Grilling Session 8): authority checks must be inlined at
# the exact point where an irreversible or gated action is described.
AUTHORITY_GATED_SKILLS = {
    "conduct-work-object",
    "deploy-with-recovery",
    "implement-bounded-change",
    "verify-release-evidence",
    "review-outcome-and-adapt",
    "diagnose-production-incident",
    "maintain-working-method",
    "govern-scorecards",
}


def validate_authority_blocks():
    """Check that every gated skill has an inline authority block.

    Returns list of (skill_name, error_message) for each missing block.
    An authority block is identified by the pattern:
        **Authority gate:** ... references/CONSEQUENCE-AUTHORITY.md
    """
    errors = []
    for skill_dir in sorted(CORE_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_name = skill_dir.name
        if skill_name not in AUTHORITY_GATED_SKILLS:
            continue
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            errors.append((skill_name, "SKILL.md not found"))
            continue
        body = skill_file.read_text()
        if "**Authority gate:**" not in body:
            errors.append((skill_name, "missing inline authority gate block"))
        elif "CONSEQUENCE-AUTHORITY.md" not in body:
            errors.append((skill_name,
                          "authority gate present but does not reference CONSEQUENCE-AUTHORITY.md"))
    return errors


def validate_capability_classifications():
    """Check that every capability classified on any platform is classified on all platforms.

    Per Decision 84 (Session 11): prevents latent cross-platform gaps where a
    capability is declared in one overlay but silently missing from another.

    Returns list of (capability, platform, error_message) for each gap.
    """
    errors = []
    all_caps = {}  # {capability_name: {platform: classification}}

    for platform in PLATFORMS:
        overlay_file = ADAPTERS_DIR / platform / "overlay.yaml"
        if not overlay_file.exists():
            errors.append(("—", platform, "overlay.yaml not found"))
            continue
        overlay = parse_yaml(overlay_file.read_text())
        caps = overlay.get("capabilities", {})
        for cap in caps:
            all_caps.setdefault(cap, {})[platform] = caps[cap]

    for cap, platforms in sorted(all_caps.items()):
        for platform in PLATFORMS:
            if platform not in platforms:
                errors.append(
                    (cap, platform,
                     f"classified on {sorted(platforms.keys())} but missing from {platform} overlay")
                )

    return errors


# ── Generation ────────────────────────────────────────────────────────────────

def adapter_skill_name(core_skill_name):
    """Return the public, collision-safe adapter name for a core skill."""
    return f"{SKILL_NAMESPACE}-{core_skill_name}"


def is_grilling_skill(skill_name):
    """Return True if skill_name is the grilling-session skill (full overlay).

    Matches both the core name and the adapter-prefixed name so that
    build_reference_entries works identically in generation and check paths.
    """
    return skill_name in (GRILLING_CORE_NAME, adapter_skill_name(GRILLING_CORE_NAME))


def namespace_skill_references(body):
    """Rewrite only backticked Work Studio skill references for adapters."""
    for skill_dir in sorted(CORE_DIR.iterdir(), key=lambda item: len(item.name), reverse=True):
        if skill_dir.is_dir():
            public_name = adapter_skill_name(skill_dir.name)
            aliases = {skill_dir.name}
            category, separator, legacy_name = skill_dir.name.partition("-")
            if separator:
                aliases.add(legacy_name)
            for alias in sorted(aliases, key=len, reverse=True):
                body = body.replace(f"`{alias}`", f"`{public_name}`")
    return body


# Core skills whose sections are intentionally different and
# should NOT receive the shared preamble injection (WO 2026-07-27-009).
#
# design-track-components and governance-maintain-working-method were moved off
# this whole-skill list to the per-section lists below (WO 2026-08-09-006). Both
# differ only in specific sections; the whole-skill skip also excluded their
# ordinary `## Output template`, which silently withheld the director-language
# preamble from two skills that had no conflicting content there.
SHARED_PREAMBLE_SKIP_SKILLS = {
    "thinking-grilling-session",
}

# Per-section skip lists for sections whose shared preamble only applies
# to a subset of skills with that heading (WO 2026-07-27-011).
SHARED_PREAMBLE_PER_SECTION_SKIP = {
    "## Work Object updates": {
        "design-design-tracer-bullet",
        "engineering-implement-bounded-change",
        "engineering-verify-release-evidence",
        "governance-conduct-work-object",
        "governance-govern-scorecards",
        "governance-review-outcome-and-adapt",
        "thinking-develop-idea",
        "thinking-pressure-test-decision",
        "thinking-turn-signal-into-work",
        "governance-maintain-working-method",
    },
    "## Consequence and authority rules": {
        "design-track-components",
        "governance-maintain-working-method",
    },
    "## Grilling entry and stage lens": {
        "design-track-components",
        "governance-maintain-working-method",
    },
}


def inject_shared_preamble(body, skill_name=None):
    """For each registered preamble section, inject shared preamble if missing.

    Core skills have shared preamble stripped (WO 2026-07-27-009). This
    function re-inserts it at generation time so that generated adapters
    remain semantically equivalent.

    Skills in SHARED_PREAMBLE_SKIP_SKILLS are left as-is (they have completely
    different content for the registered heading). Per-section skip lists in
    SHARED_PREAMBLE_PER_SECTION_SKIP exclude specific skills from receiving
    the shared preamble for a particular heading (WO 2026-07-27-011).
    """
    if skill_name in SHARED_PREAMBLE_SKIP_SKILLS:
        return body
    for heading, ref_path in SHARED_PREAMBLE_SECTIONS.items():
        if heading not in body:
            continue
        # Check per-section skip list
        section_skips = SHARED_PREAMBLE_PER_SECTION_SKIP.get(heading, set())
        if skill_name in section_skips:
            continue
        preamble = ref_path.read_text().strip()
        idx = body.index(heading)
        after_heading = body[idx + len(heading):]
        # Skip blank lines after the heading
        rest = after_heading.lstrip("\n")
        # Check if preamble is already present (e.g. design-track-components
        # which has an extended preamble not suitable for extraction)
        first_line = rest.split("\n", 1)[0] if rest else ""
        if first_line and not first_line.startswith("Apply `"):
            injection = "\n\n" + preamble + "\n\n"
            body = body[:idx + len(heading)] + injection + rest
    return body


def build_skill_output(core_skill_dir, overlay):
    """Build the exact adapter SKILL.md text for a core skill + overlay.

    Single source of truth for both generation and drift checking, so the two
    paths can never diverge.
    """
    body = namespace_skill_references(extract_body(core_skill_dir / "SKILL.md"))
    body = inject_shared_preamble(body, core_skill_dir.name)
    frontmatter = generate_frontmatter(core_skill_dir, overlay)
    default_tier = extract_default_tier(core_skill_dir)
    adapter_section = generate_adapter_section(
        overlay, required_capabilities(core_skill_dir), default_tier)
    output = frontmatter + body.rstrip("\n") + adapter_section
    # Ensure exactly one trailing newline
    return output.rstrip("\n") + "\n"


def generate_skill(core_skill_dir, overlay, output_dir):
    """Generate one adapter skill from core + overlay."""
    core_file = core_skill_dir / "SKILL.md"
    skill_name = core_skill_dir.name
    output_skill_name = adapter_skill_name(skill_name)

    if not core_file.exists():
        print(f"  SKIP {skill_name}: core file not found at {core_file}")
        return None

    output = build_skill_output(core_skill_dir, overlay)

    # Prompt budget warning per tier (advisory, not blocking — DEC-5)
    default_tier = extract_default_tier(core_skill_dir)
    prompt_budgets = overlay.get("prompt_budgets", {})
    if prompt_budgets:
        budget = prompt_budgets.get(default_tier)
        if budget is not None and len(output) > budget:
            print(f"  WARNING: {output_skill_name} ({default_tier}) "
                  f"output size {len(output)} exceeds budget {budget}")

    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "SKILL.md"
    output_file.write_text(output)

    checksum = hashlib.sha256(output.encode()).hexdigest()
    return {
        "name": output_skill_name,
        "path": str(output_file.relative_to(ROOT)),
        "sha256": checksum,
    }


def build_reference_entries(skill_name, output_dir, core_skill_dir=None, write=False):
    """Include shared references that the skill body actually mentions.

    Scans the canonical skill body for each shared reference filename and
    only copies files the skill explicitly references (Decision 88, Session 11).
    When core_skill_dir is None (legacy path), includes all references.

    Kernel/overlay split (Decision 3, WO 2026-07-26-004): grilling overlay
    references (AGREEMENT-LOOP.md, SKILL-AWARE-GRILLING.md) are filtered out
    for all skills except grilling-session, which gets the full overlay.

    Tier-scaled epistemic rules (WO 2026-07-26-006): the correct epistemic
    reference variant is included based on the skill's default_tier.
    """
    entries = []
    reference_dir = output_dir / "references"

    if core_skill_dir is not None:
        body = extract_body(core_skill_dir / "SKILL.md")
        active_refs = [f for f in SHARED_REFERENCES if Path(f).name in body]
        # Shared preamble sections may reference additional files not present
        # in the stripped body (WO 2026-07-27-009). Include them so that
        # companion reference files are still shipped with generated adapters.
        skill_name_clean = core_skill_dir.name if core_skill_dir else skill_name
        if skill_name_clean not in SHARED_PREAMBLE_SKIP_SKILLS:
            for heading, ref_path in SHARED_PREAMBLE_SECTIONS.items():
                if heading in body:
                    preamble = ref_path.read_text()
                    for ref in SHARED_REFERENCES:
                        if ref not in active_refs and ref in preamble:
                            active_refs.append(ref)
    else:
        active_refs = SHARED_REFERENCES

    # Kernel/overlay split: grilling overlay references only ship with the
    # grilling-session skill. All other skills get kernel-only output.
    if not is_grilling_skill(skill_name):
        active_refs = [f for f in active_refs if f not in GRILLING_OVERLAY_REFS]

    if write:
        if active_refs:
            reference_dir.mkdir(parents=True, exist_ok=True)
            # Remove stale reference files no longer mentioned by this skill
            active_names = {Path(f).name for f in active_refs}
            for existing in reference_dir.iterdir():
                if existing.is_file() and existing.name not in active_names:
                    existing.unlink()
        elif reference_dir.exists():
            shutil.rmtree(reference_dir)
    for filename in active_refs:
        source = ROOT / "references" / filename
        destination = reference_dir / Path(filename).name
        content = source.read_bytes()
        if write:
            shutil.copyfile(source, destination)
        entries.append({
            "name": f"{skill_name}/references/{filename}",
            "path": str(destination.relative_to(ROOT)),
            "sha256": hashlib.sha256(content).hexdigest(),
        })

    # Tier-scaled epistemic rules variant (WO 2026-07-26-006)
    if core_skill_dir is not None:
        default_tier = extract_default_tier(core_skill_dir)
        epistemic_tier = resolve_epistemic_tier(default_tier)
        variant_filename = epistemic_variant_filename(epistemic_tier)
        # Use a consistent reference name so the Platform Adapter section can
        # reference it without knowing the tier at body-writing time.
        epistemic_source = EPISTEMIC_REF_DIR / variant_filename
        if epistemic_source.exists():
            epistemic_dest = reference_dir / "epistemic" / variant_filename
            content = epistemic_source.read_bytes()
            # epistemic-rules-full.md points at AGREEMENT-LOOP.md's tag table
            # instead of restating it; ship a generated excerpt alongside it
            # so the pointer resolves even where AGREEMENT-LOOP.md itself is
            # excluded by the grilling overlay split.
            needs_excerpt = variant_filename == "epistemic-rules-full.md"
            keep_names = {variant_filename}
            if needs_excerpt:
                keep_names.add(AGREEMENT_LOOP_TAG_EXCERPT_FILENAME)
            if write:
                epistemic_dest.parent.mkdir(parents=True, exist_ok=True)
                # Remove stale epistemic variants/excerpts for this skill
                if epistemic_dest.parent.exists():
                    for existing in epistemic_dest.parent.iterdir():
                        if existing.is_file() and existing.name not in keep_names:
                            existing.unlink()
                epistemic_dest.write_bytes(content)
            entries.append({
                "name": f"{skill_name}/references/epistemic/{variant_filename}",
                "path": str(epistemic_dest.relative_to(ROOT)),
                "sha256": hashlib.sha256(content).hexdigest(),
            })
            if needs_excerpt:
                excerpt_content = extract_agreement_loop_tag_excerpt()
                excerpt_dest = epistemic_dest.parent / AGREEMENT_LOOP_TAG_EXCERPT_FILENAME
                if write:
                    excerpt_dest.write_bytes(excerpt_content)
                entries.append({
                    "name": f"{skill_name}/references/epistemic/{AGREEMENT_LOOP_TAG_EXCERPT_FILENAME}",
                    "path": str(excerpt_dest.relative_to(ROOT)),
                    "sha256": hashlib.sha256(excerpt_content).hexdigest(),
                })

    return entries


def generate_platform(platform_name):
    """Generate all adapter skills for one platform."""
    overlay_file = ADAPTERS_DIR / platform_name / "overlay.yaml"

    if not overlay_file.exists():
        print(f"SKIP {platform_name}: overlay not found")
        return []

    overlay_text = overlay_file.read_text()
    overlay = parse_yaml(overlay_text)

    output_base = ADAPTERS_DIR / platform_name / "skills"
    expected_dirs = {adapter_skill_name(path.name) for path in CORE_DIR.iterdir()
                     if path.is_dir()}
    if output_base.exists():
        for child in output_base.iterdir():
            if child.is_dir() and child.name not in expected_dirs:
                shutil.rmtree(child)
    manifest_entries = []

    for skill_dir in sorted(CORE_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        output_skill_name = adapter_skill_name(skill_dir.name)
        output_dir = output_base / output_skill_name
        entry = generate_skill(skill_dir, overlay, output_dir)
        if entry:
            manifest_entries.append(entry)
            print(f"  Generated: {entry['path']} ({entry['sha256'][:12]}...)")
            manifest_entries.extend(
                build_reference_entries(output_skill_name, output_dir, core_skill_dir=skill_dir, write=True))

    return manifest_entries


# ── Manifest ──────────────────────────────────────────────────────────────────

def build_manifest(platform_name, entries):
    """Build the manifest dict for a platform. Deterministic (no timestamps)."""
    return {
        "platform": platform_name,
        "version": read_version(),
        "generated_by": "tools/generate-adapters.py",
        "files": entries,
    }


def write_manifest(platform_name, entries):
    """Write per-platform manifest.json with checksums."""
    manifest_dir = ADAPTERS_DIR / platform_name
    manifest_dir.mkdir(parents=True, exist_ok=True)

    manifest = build_manifest(platform_name, entries)
    manifest_path = manifest_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"  Manifest: {manifest_path.relative_to(ROOT)}")


def build_checksums(platform_name, entries):
    """Build SHA256SUMS text: `<sha256>  <path-relative-to-adapter-dir>`.

    Paths are relative to `adapters/<platform>/` so the installer can `cd`
    into the adapter directory and run `shasum -a 256 -c SHA256SUMS` with no
    other tooling. Sorted by path for deterministic output.
    """
    adapter_dir = ADAPTERS_DIR / platform_name
    rows = []
    for entry in entries:
        rel = Path(entry["path"]).relative_to(Path("adapters") / platform_name)
        rows.append((str(rel), entry["sha256"]))
    rows.sort()
    return "".join(f"{sha}  {rel}\n" for rel, sha in rows)


def write_checksums(platform_name, entries):
    """Write per-platform SHA256SUMS for dependency-free runtime verification."""
    manifest_dir = ADAPTERS_DIR / platform_name
    manifest_dir.mkdir(parents=True, exist_ok=True)
    sums_path = manifest_dir / "SHA256SUMS"
    sums_path.write_text(build_checksums(platform_name, entries))
    print(f"  Checksums: {sums_path.relative_to(ROOT)}")


# ── Check mode ────────────────────────────────────────────────────────────────

def check_platform(platform_name):
    """Verify generated files match what would be regenerated. Returns True if clean."""
    overlay_file = ADAPTERS_DIR / platform_name / "overlay.yaml"
    if not overlay_file.exists():
        print(f"SKIP {platform_name}: overlay not found")
        return True

    overlay_text = overlay_file.read_text()
    overlay = parse_yaml(overlay_text)

    output_base = ADAPTERS_DIR / platform_name / "skills"
    all_clean = True
    expected_entries = []

    for skill_dir in sorted(CORE_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_name = skill_dir.name
        output_skill_name = adapter_skill_name(skill_name)
        output_file = output_base / output_skill_name / "SKILL.md"

        expected = build_skill_output(skill_dir, overlay)

        if not output_file.exists():
            print(f"  MISSING: {output_file.relative_to(ROOT)}")
            all_clean = False
            continue

        actual = output_file.read_text()
        if actual != expected:
            print(f"  DRIFT: {output_file.relative_to(ROOT)}")
            all_clean = False
        else:
            print(f"  OK: {output_file.relative_to(ROOT)}")

        expected_entries.append({
            "name": output_skill_name,
            "path": str(output_file.relative_to(ROOT)),
            "sha256": hashlib.sha256(expected.encode()).hexdigest(),
        })

        for entry in build_reference_entries(output_skill_name, output_file.parent, core_skill_dir=skill_dir):
            reference_file = ROOT / entry["path"]
            if not reference_file.exists():
                print(f"  MISSING: {reference_file.relative_to(ROOT)}")
                all_clean = False
            elif hashlib.sha256(reference_file.read_bytes()).hexdigest() != entry["sha256"]:
                print(f"  DRIFT: {reference_file.relative_to(ROOT)}")
                all_clean = False
            expected_entries.append(entry)

    # Check manifest
    manifest_path = ADAPTERS_DIR / platform_name / "manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
            if manifest != build_manifest(platform_name, expected_entries):
                print(f"  MANIFEST DRIFT: {manifest_path.relative_to(ROOT)}")
                all_clean = False
            else:
                print(f"  MANIFEST OK: {manifest_path.relative_to(ROOT)}")
        except (json.JSONDecodeError, KeyError) as e:
            print(f"  MANIFEST ERROR: {manifest_path.relative_to(ROOT)}: {e}")
            all_clean = False
    else:
        print(f"  MANIFEST MISSING: {manifest_path.relative_to(ROOT)}")
        all_clean = False

    # Check SHA256SUMS
    sums_path = ADAPTERS_DIR / platform_name / "SHA256SUMS"
    expected_sums = build_checksums(platform_name, expected_entries)
    if not sums_path.exists():
        print(f"  CHECKSUMS MISSING: {sums_path.relative_to(ROOT)}")
        all_clean = False
    elif sums_path.read_text() != expected_sums:
        print(f"  CHECKSUMS DRIFT: {sums_path.relative_to(ROOT)}")
        all_clean = False
    else:
        print(f"  CHECKSUMS OK: {sums_path.relative_to(ROOT)}")

    return all_clean


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if "--check" in sys.argv:
        print("Checking generated adapters...")
        all_clean = True
        for platform in PLATFORMS:
            print(f"\n[{platform}]")
            if not check_platform(platform):
                all_clean = False
        # Validate authority blocks in core skills
        auth_errors = validate_authority_blocks()
        if auth_errors:
            print("\n[authority-blocks]")
            for skill, err in auth_errors:
                print(f"  FAIL: {skill}: {err}")
            all_clean = False
        else:
            print("\n[authority-blocks]")
            print("  OK: all gated skills have inline authority blocks")
        # Validate symmetric capability classifications across overlays
        cap_errors = validate_capability_classifications()
        if cap_errors:
            print("\n[capability-classifications]")
            for cap, platform, err in cap_errors:
                print(f"  FAIL: {cap}: {platform}: {err}")
            all_clean = False
        else:
            print("\n[capability-classifications]")
            print("  OK: all capabilities classified on all platforms")
        if all_clean:
            print("\nAll generated files match. No drift detected.")
            sys.exit(0)
        else:
            print("\nDRIFT DETECTED. Run 'python3 tools/generate-adapters.py' to regenerate.")
            sys.exit(1)
    else:
        # Validate authority blocks before generating
        auth_errors = validate_authority_blocks()
        if auth_errors:
            print("Authority block validation failed:")
            for skill, err in auth_errors:
                print(f"  FAIL: {skill}: {err}")
            print("Add inline authority gate blocks before regenerating.")
            sys.exit(1)
        # Validate symmetric capability classifications before generating
        cap_errors = validate_capability_classifications()
        if cap_errors:
            print("Capability classification validation failed (Decision 84):")
            for cap, platform, err in cap_errors:
                print(f"  FAIL: {cap}: {platform}: {err}")
            print("Classify every capability on all three platforms before regenerating.")
            sys.exit(1)
        print("Generating adapters...")
        for platform in PLATFORMS:
            print(f"\n[{platform}]")
            entries = generate_platform(platform)
            if entries:
                write_manifest(platform, entries)
                write_checksums(platform, entries)
        print("\nDone. Run 'python3 tools/generate-adapters.py --check' to verify.")


if __name__ == "__main__":
    main()
